apiVersion: v2
name: xen-orchestra-community
description: Community Xen Orchestra container (XO6 preview built) packaged as a Helm chart
type: application
version: "5.51.0-a"
appVersion: "5.51.0a"
home: https://github.com/fractalnomad/XenOrchestraCommunity
maintainers:
- name: FractalNomad
  url: https://github.com/fractalnomad
