apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xoc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "xoc.name" . }}
    helm.sh/chart: {{ include "xoc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xoc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "xoc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: xo
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/xo-server/data
            - name: config
              mountPath: /home/xo/.config/xo-server/config.toml
              subPath: config.toml
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "xoc.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "xoc.fullname" . }}-config
